Considere uma cadeia circular composta por  átomos, cada um de massa , conectados por molas idênticas de constante elástica . O sistema está sujeito a condições de contorno ou seja a primeira massa está ligada a última massa. Em uma das simulações, introduza um defeito de molas:  substitua duas molas que ligam uma massa por (k2=5k)
 
Parâmetros
• Massas padrão:  m=1 kg
 • Constante elástica: k = 1 N/m
 • Tamanhos da cadeia: N = 100, 1000 e 10.000
• Defeito: massa igual a k2 = 5k  (apenas em uma das simulações)
 
Tarefas  
1. Cálculo das Frequências de Vibração  
• Para cada valor de  (100, 1000, 10000), calcule as frequências naturais de vibração do sistema para:  
• Cadeia homogênea (todas as massas iguais)  
• Cadeia com defeito de massa no centro  
2. Densidade de Estados  
• Construa histogramas (densidade de estados) para os valores de  obtidos em cada caso.  
• Compare os histogramas para diferentes tamanhos de cadeia e para a presença/ausência do defeito.  
3. Deslocamentos Relativos (Modos Normais)  
• Para cada cadeia, obtenha os vetores de deslocamento (modos normais) correspondentes:  
• Às cinco menores frequências (modos de baixa energia)  
• Às cinco maiores frequências (modos de alta energia)  
• Apresente gráficos dos deslocamentos relativos dos átomos para esses modos.  
4. Análise e Comparação  
• Analise como o tamanho da cadeia e a presença do defeito afetam:  
• A distribuição das frequências (densidade de estados)  
• Os padrões de deslocamento dos modos normais  
• Discuta a localização dos modos associados ao defeito de massa.  
Orientações para Implementação em Python  
• O código deve ser bem documentado e comentado, facilitando o entendimento de cada etapa do processo.  
• Utilize bibliotecas como `numpy` e `matplotlib` para cálculos e visualizações.  
• Monte a matriz dinâmica do sistema e calcule seus autovalores e autovetores.  
• Para grandes valores de , otimize o código para eficiência computacional.  
• Disponibilize o código final em um repositório no GitHub e inclua o link no relatório.  
   
Instruções para Entrega  
 • A resposta deve ser enviada via Moodle devidamente comentada.  
• Inclua todos os gráficos gerados (histogramas, modos normais, etc.) no arquivo de resposta, pois não será possível rodar todos os programas novamente para correção.  
• Certifique-se de que cada gráfico esteja devidamente identificado e relacionado ao caso analisado.  
   
Sugestão de Estrutura para a resposta  
1. Introdução  
• Breve explicação do modelo massa-mola e sua relevância para cadeias atômicas.  
2. Metodologia  
• Descrição do método numérico utilizado para calcular frequências e modos.  
3. Resultados  
• Histogramas das densidades de estados para cada caso.  
• Gráficos dos deslocamentos relativos para os modos selecionados.  
• Tabela comparativa dos principais resultados.  
4. Discussão  
• Interpretação dos efeitos do tamanho da cadeia e do defeito de massa.    
• Observações sobre a localização dos modos e possíveis aplicações.  
5. Conclusão  
• Síntese dos principais achados.  
Observação: Comente o código de forma clara, disponibilize o link do GitHub e anexe todos os gráficos no Moodle para garantir a avaliação completa.  

In [11]:
import numpy as np
import matplotlib.pyplot as plt
from scipy.linalg import eigh
from scipy.sparse import diags, csr_matrix
import pandas as pd

In [2]:
#Parâmetros
m_var, k1, k2 = 1, 1, 5
N1, N2, N3 = 100, 1000, 10000

### Cadeia de 100 átomos

In [9]:

# Cria a matriz nula
m = []
for i in range(int(N1)): 
    m.append(float(m_var))
m = np.array(m)


# Inicializa a matriz D com zeros
D100 = np.zeros((N1, N1))

# Preenche a matriz D de acordo com o sistema de massas e molas
for i in range(N1):
    if N1 == 1:  # Caso especial com apenas 1 massa
        D100[i, i] = k1/m[i]
    else:
        if i == 0:  # Primeira massa
            D100[i, i] = 2*k1/m[i]
            D100[i, i+1] = -k1/m[i]
        elif i == N1-1:  # Última massa
            D100[i, i] = 2*k1/m[i]
            D100[i, i-1] = -k1/m[i]
        else:  # Massas do meio
            D100[i, i] = 2*k1/m[i]
            D100[i, i-1] = -k1/m[i]
            D100[i, i+1] = -k1/m[i]

ww_100, v_100 = eigh(D100)
w = np.sqrt(ww_100) 

print("Matriz D:")
print(D100)

Matriz D:
[[ 2. -1.  0. ...  0.  0.  0.]
 [-1.  2. -1. ...  0.  0.  0.]
 [ 0. -1.  2. ...  0.  0.  0.]
 ...
 [ 0.  0.  0. ...  2. -1.  0.]
 [ 0.  0.  0. ... -1.  2. -1.]
 [ 0.  0.  0. ...  0. -1.  2.]]


Por tratar-se de uma matriz tridiagonal, é mais eficiente armazená-la como `csr_matrix` (Compressed Sparse Row), pois economiza RAM e é otimizada para operações matriciais como cálculo de autovalores e autovetores. Para matrizes $D_{100 \times 100}$ não faz muita diferença mas no caso de matrizes grandes — $D_{10000 \times 10000}$ , por exemplo —, faz.

A diagonal principal é $\frac{2k_1}{m_{var}}$ e as adjacentes são $\frac{k_1}{m_{var}}$

In [12]:
dg100_principal = np.ones(N1) * (2*k1/m_var)
dg100_adjacentes = np.ones(N1-1) * (-k1/m_var)
D100_diag = diags([dg100_adjacentes, dg100_principal, dg100_adjacentes], 
                offsets = [-1, 0, 1], 
                shape=(N1, N1))
D100_csr = csr_matrix(D100_diag)

Autovalores, autovetores e frequências ($\omega$)

### Cadeia de 1000 átomos

In [15]:
dg1000_principal = np.ones(N2) * (2*k1/m_var)
dg1000_adjacentes = np.ones(N2-1) * (-k1/m_var)
D1000_diag = diags([dg1000_adjacentes, dg1000_principal, dg1000_adjacentes], 
                offsets = [-1, 0, 1], 
                shape=(N2, N2))
D1000_csr = csr_matrix(D1000_diag)

### Cadeia de 10000 átomos

In [16]:
dg10000_principal = np.ones(N3) * (2*k1/m_var)
dg10000_adjacentes = np.ones(N3-1) * (-k1/m_var)
D10000_diag = diags([dg10000_adjacentes, dg10000_principal, dg10000_adjacentes], 
                offsets = [-1, 0, 1], 
                shape=(N3, N3))
D10000_csr = csr_matrix(D10000_diag)

In [ ]:
ww_10000, v_10000 = eigh(D10000)
w = np.sqrt(ww_10000) 